### ISSUE TITLE
[Feature request] Multiple genres

### ISSUE THREAD

**Issue by van-de-bugger** [TJYSunset/Phocid#26]
Hi,

Thanks for the player. I like the "multiple artists" feature - there are only a few Android players that support a one-to-many relationship between album/track and artists.

The same idea applies to genres, though. A track can have more than one genre associated with it. It would be nice if Phocid splitted genres the same way it splitted artists. (Really, I do not think similar flexibility is actually required. One dedicated character (like semicolon) would be enough.)

**Comment by TJYSunset** [comment]
Multiple genres are already supported, if you enable "Advanced metadata extraction" in preferences then tag the files like so in Mp3tag:

![Right click on the track, then click on "Extended tags..."](https://github.com/user-attachments/assets/5ce9e43b-909c-49cd-9f75-a45bd516e792)
![Add multiple "GENRE" fields](https://github.com/user-attachments/assets/8bd8aec0-3dbc-43ad-8eb2-e826b8458937)

Since genre is a lesser used feature, I assume people wanting better genre support will have already tagged them "properly" as demonstrated.

If you still insist on smart genre separation being necessary, I'll take a look later.

**Comment by van-de-bugger** [comment]
Thanks for the quick reply. I'm not pushing for any particular approach. However, I would prefer a unified solution. If Phocid handles multi-valued tags, that's just perfect. Does this also apply to artists? In that case, why did you implement artist separators?

**Comment by TJYSunset** [comment]
> Does this also apply to artists?

Yes.

> why did you implement artist separators?

Because most tracks come tagged "improperly" when distributed, and people might have already intentionally tagged their tracks "improperly" as a workaround for players without such support.

Considering your use case described in #28, seems that a solution without relying on "advanced metadata extraction" is actually required. I'll work on that.

**Comment by van-de-bugger** [comment]
> Because most tracks come tagged "improperly" when distributed…

I keep my library properly and correctly tagged. I can relatively easilyy convert multiple values to single value with separator, so either way will work to me.

Thanks for reply. Feel free to either close the ticket or keep it open to plan your work.

**Comment by TJYSunset** [comment]
Added in 3437ac591112ce2da9d6a476f47278ccb763e1fb
