### ISSUE TITLE
support m3u playlists?

### ISSUE THREAD

**Issue by secretmango** [TJYSunset/Phocid#6]
Hi there!

I really like the design of the player. Currently I use [Anrimians music player](https://github.com/Anrimian/music-player) which has a few essential features.

One of them is that it stores playlists in the /storage/emulated/0/Music directory as .m3u files.

They dynamically reference the music files, so having all music there too, makes it really easy to sync it to my Linux PC, where I use G4Music (or others too) and can use these playlists just as well.

Currently the app does not read or write playlists here. What do you think?

**Comment by TJYSunset** [comment]
Playlist import button is in the top-right overflow menu when you are on the playlist tab. I agree it's hard to discover, but that's where the original Phonograph put it, and using a floating action button is not a good idea (I've tried that).

**Comment by TJYSunset** [comment]
Closing this for now since it's already implemented. If you have a better idea of where to locate the button, feel free to comment.

(Showing it on every tab is not an option, or I'll get a issue for undesirable menu clutter next.)

**Comment by secretmango** [comment]
A question, will the import also make Phocid update the m3u files to resemble the playlists?

**Comment by TJYSunset** [comment]
Since syncing user changes back to m3u files without ever breaking their m3us is not possible (m3u has no strict formal standards), currently the other way around is also not implemented.

Reading m3us is also error-prone; My player on PC exports m3us as absolute paths with no option to make it relative (and probably many other popular players are the same), so Phocid (and other players) has to make a best-effort guess to import without having the user manually editing m3us.
